name: Build
on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - name: Checkout main branch in repository
        uses: actions/checkout@v5
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: |
          npm install
      - name: Build
        run: npm run build
      - name: Archive testing report as artifact
        uses: actions/upload-artifact@v4
        if: always()
        with: 
          name: report
          path: report/
          retention-days: 2
